### ISSUE TITLE
Please document dependency on inkscapeMadeEasy_Base.py

### ISSUE THREAD

**Issue by jaimet** [hawley577/Inkscape-Rounded-Corners#2]
I followed the installation instructions, but the extension didn't show up in inkscape's extensions menu. The inkscape extension error file (extension-errors.log) told me that I was missing inkscapeMadeEasy_Base.py, so a quick `wget -O ~/.config/inkscape/extensions/inkscapeMadeEasy_Base.py https://github.com/fsmMLK/inkscapeMadeEasy/raw/master/inkscapeMadeEasy_Base.py` fixed the problem. I *then* discovered the already-closed https://github.com/hawley577/Inkscape-Rounded-Corners/issues/1 issue which is exactly the same problem. Could you please modify the "Installation" section of the wiki page to let people know? Many thanks for your fantastic extension BTW - it's much appreciated!

**Comment by hawley577** [comment]
Added note in the wiki about inkscapeMadeEasy dependency.
