### ISSUE TITLE
Radius offset when using base unit mm

### ISSUE THREAD

**Issue by Mounty2010** [hawley577/Inkscape-Rounded-Corners#3]
Hello, 
i tried your inkscape addon on inkscape 0.92.2 and encountered an issue.
There seem to be an offset of 0.05mm per mm of the radius. For example:

i have to type in radius of 7.6 (base unit: mm) to get a real radius of 8mm.
i have to type in radius of 3.8 (base unit: mm) to get a real radius of 4mm.
i have to type in radius of 1.9 (base unit: mm) to get a real radius of 2mm.

This equals an offset of 0.05mm per 1mm of the desired radius, which makes
it easy to calculate for me, but would be nice, if this can be sorted out and get
fixed. I used just simple (filled) circles (without outline/stroke) for comparison.

I dont use objects with stroke paint (stroke disabled) just filled objects.
Most of the time i also use View -> Display Mode ->  Outline so i dont
have to deal with borders / strokes.

**Comment by Mounty2010** [comment]
In addition to that confusing behavior i have a question, because i dont get it.
When using for example radius of 8mm (7.6mm), a circle of 4mm diameter fits 
into this rounded edge. A circle with diameter of 4mm only has radius of 2mm,
how can it be, that this circle fits into a rounded corner with 8mm radius ?

**Comment by Mounty2010** [comment]
Okay forget about it. I dont know what happened, but now it is working like expected.
I created some new objects, converted to path, tried again your rounded corners addon
and everything worked like charm. When i now set radius of 2mm, the 4mm diameter
circle fits perfectly into the rounded corner. Don't understand the strange behaviour
i got first. 

You can close / delete this issue, its gone now.

**Comment by hawley577** [comment]
I'll leave this open for a while.  If you or anyone else have a similar issue I'd like have the inkscape file sent to me so I can examine it and determine the problem. Thanks!
